name: version, tag and github release

on:
  push:
    branches:
      - main
      - prerelease/*
    tags-ignore:
      - "*"

jobs:
  release:
    # this job will throw if prerelease is true but it doesn't have a prerelease-looking package.json version
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@main
    secrets: inherit
    with:
      prerelease: ${{ github.ref_name != 'main' }}